### ISSUE TITLE
iOS Device Orientation needs setting Landscape only

### ISSUE THREAD

**Issue by AndyDentFree** [MontanaFlossCo/FlintDemo-iOS#16]
The app only shows a white screen if built and run on an iPhone as currently shipped.

The split-view UI only works in a landscape orientation, so the project needs changing to only have landscape orientations checked. Maybe a better way is to have separate iPad and iPhone settings - I don't know because I haven't done any iPad layout.

(Trivial so thought I'd just throw an issue in here rather than forking and submitting a PR).

**Comment by marcpalmer** [comment]
Actually I will just fix the split view. It should be a fully functioning universal app, with split view support on plus phones. :)

**Comment by marcpalmer** [comment]
Fixed by #18
